FROM ubuntu:22.04

ARG VERSION
ARG TARGETPLATFORM
ENV TARGETPLATFORM=${TARGETPLATFORM}

COPY . .

RUN chmod u+x ./install-prereq.sh && ./install-prereq-linux.sh
RUN chmod u+x ./install-nadeko.sh && ./install-nadeko-linux.sh
RUN chmod u+x ./run-nadeko-linux.sh

CMD ["/bin/bash", "-c", "./run-nadeko-linux.sh"]
