name: Check for New Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Option to run manually

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest GitLab release
        run: |
          curl -s https://gitlab.com/api/v4/projects/9321079/releases | jq -r '.[0].tag_name' > gitlab_release.txt
          echo "Latest GitLab release: $(cat gitlab_release.txt)"

      - name: Get DockerHub tags
        run: |
          curl -s https://hub.docker.com/v2/repositories/ryuunosukeds3/nadeko-bot-docker/tags | jq -r '.results[].name' > dockerhub_tags.txt
          echo "DockerHub tags: $(cat dockerhub_tags.txt)"

      - name: Compare versions
        id: version_check
        run: |
          GITLAB_VERSION=$(cat gitlab_release.txt)
          DOCKERHUB_VERSIONS=$(cat dockerhub_tags.txt)
          if echo "$DOCKERHUB_VERSIONS" | grep -q "$GITLAB_VERSION"; then
            echo "Version already exists on DockerHub: $GITLAB_VERSION"
            echo "new_version=false" >> $GITHUB_ENV
          else
            echo "New version found: $GITLAB_VERSION"
            echo "new_version=true" >> $GITHUB_ENV
            echo "version=$GITLAB_VERSION" >> $GITHUB_ENV
          fi

      - name: Trigger Docker Build Workflow
        if: env.new_version == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { version } = process.env;
            const { owner, repo } = context.repo;
            await github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: repo,
              workflow_id: 'publish-to-dockerhub.yml',  // The name of the second workflow file
              ref: 'v5',  // Branch to run the workflow on
              inputs: {
                logLevel: 'run',
                version: version
              }
            });
