name: Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'run'
        required: true
        type: choice
        options:
          - run
      version:
        description: 'Version to build and publish'
        required: true
      latest:
        description: 'Tag as latest?'
        required: false
        type: boolean
        default: false

jobs:
  windows_docker_amd64:
    permissions:
      actions: write
      contents: read
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get lowercase repo name
        id: repo_name
        shell: pwsh
        run: |
          $repo = "${{ github.repository }}".ToLower()
          Write-Output "REPO_NAME=$repo" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Check repo name lowercase
        shell: pwsh
        run: |
          Write-Output $env:REPO_NAME

      - name: Set up Docker Buildx (Windows)
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows Dockerfile (amd64)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.windows
          platforms: windows/amd64
          push: true
          tags: |
            ${{ env.REPO_NAME }}:${{ github.event.inputs.version }}
            ${{ github.event.inputs.latest && format('{0}:latest', env.REPO_NAME) }}

  windows_docker_arm64:
    permissions:
      actions: write
      contents: read
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get lowercase repo name
        id: repo_name
        shell: pwsh
        run: |
          $repo = "${{ github.repository }}".ToLower()
          Write-Output "REPO_NAME=$repo" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Check repo name lowercase
        shell: pwsh
        run: |
          Write-Output $env:REPO_NAME

      - name: Set up Docker Buildx (Windows)
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows Dockerfile (arm64)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.windows
          platforms: windows/arm64
          push: true
          tags: |
            ${{ env.REPO_NAME }}:${{ github.event.inputs.version }}
            ${{ github.event.inputs.latest && format('{0}:latest', env.REPO_NAME) }}

  linux_docker:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get lowercase repo name
        id: repo_name
        run: echo "REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check reponame lowercase
        run: echo ${{ env.REPO_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Linux Dockerfile
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.linux
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REPO_NAME }}:${{ github.event.inputs.version }}
            ${{ github.event.inputs.latest && format('{0}:latest', env.REPO_NAME) }}
